# Generated by Django 4.1 on 2022-11-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='String_Concatenation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string1', models.CharField(blank=True, max_length=128)),
                ('string2', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='String_Multiplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_for_multiplication', models.CharField(max_length=128)),
                ('n', models.IntegerField()),
            ],
        ),
    ]
